In [1]:
import numpy as np

In [2]:
a = np.zeros((2,2))
b = np.ones((2,2))

In [3]:
np.sum(b, axis=1)

array([ 2.,  2.])

In [4]:
a.shape

(2, 2)

In [5]:
np.reshape(a, (1,4))

array([[ 0.,  0.,  0.,  0.]])

In [6]:
import tensorflow as tf

In [7]:
tf.InteractiveSession()

In [8]:
a = tf.zeros((2,2))
b = tf.ones((2,2))
print(a)
print(tf.reduce_sum(b, reduction_indices=1).eval())
print(a.get_shape())

Tensor("zeros:0", shape=(2, 2), dtype=float32)
[ 2.  2.]
(2, 2)


In [9]:
print(tf.reshape(a, (1,4)))
print(tf.reshape(a, (1,4)).eval())

Tensor("Reshape:0", shape=(1, 4), dtype=float32)
[[ 0.  0.  0.  0.]]
