# Session Object

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
print(a)
print(b)
print(c)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("mul:0", shape=(), dtype=float32)


In [3]:
with tf.Session() as sess:
    print(sess.run(c))
    print(c.eval())

30.0
30.0


# Variables

In [4]:
W1 = tf.ones((2,2))
W2 = tf.Variable(tf.zeros((2,2)), name="weights")

In [5]:
with tf.Session() as sess:
    print(sess.run(W1))
    sess.run(tf.global_variables_initializer())
    print("--------")
    print(sess.run(W2))

[[ 1.  1.]
 [ 1.  1.]]
--------
[[ 0.  0.]
 [ 0.  0.]]


## Variable objects can be initialized from constants or random values

In [6]:
W = tf.Variable(tf.zeros((2,2)), name="weights")
R = tf.Variable(tf.random_normal((2,2)), name="random_weights")
print(W)
print(R)

<tf.Variable 'weights_1:0' shape=(2, 2) dtype=float32_ref>
<tf.Variable 'random_weights:0' shape=(2, 2) dtype=float32_ref>


In [7]:
print(W.shape)
print(W.get_shape())

(2, 2)
(2, 2)


In [8]:
a1, b1 = W.shape
a2, b2 = W.get_shape()

In [9]:
a1

Dimension(2)

In [10]:
a2

Dimension(2)

In [11]:
for i in range(a1):
    print(i)

0
1


In [12]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(W))
    print(sess.run(R))

[[ 0.  0.]
 [ 0.  0.]]
[[-0.92752898  1.04084623]
 [-0.13601571 -0.55637223]]


## Updating Variable State

In [13]:
state = tf.Variable(0, name="counter")
print(state)

<tf.Variable 'counter:0' shape=() dtype=int32_ref>


In [14]:
new_value = tf.add(state, tf.constant(1))
print(new_value)

Tensor("Add:0", shape=(), dtype=int32)


In [15]:
update = tf.assign(state, new_value)
print(update)

Tensor("Assign:0", shape=(), dtype=int32_ref)


In [16]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


## Fetching Variable State

In [17]:
input1 = tf.constant(3.0)
input2 = tf.constant(2.0)
input3 = tf.constant(5.0)

intermed = tf.add(input2, input3)
mul = tf.multiply(input1, intermed)
with tf.Session() as sess:
    result = sess.run([mul, intermed])
    print(result)

[21.0, 7.0]


## Variable Scope

In [18]:
x = np.random.randn()
print(x)

-0.2884214693829479


In [19]:
with tf.variable_scope("foo"):
    v = tf.get_variable("v", initializer=x)
    
    tf.get_variable_scope().reuse_variables()
    v1 = tf.get_variable("v")

assert v1 == v

In [20]:
v1

<tf.Variable 'foo/v:0' shape=() dtype=float32_ref>

In [21]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    res_v, res_v1 = sess.run([v, v1])
    print(res_v, res_v1)
    
    for _ in range(3):
        v = v + 1
        print(sess.run(v))    

-0.288421 -0.288421
0.711578
1.71158
2.71158


In [22]:
with tf.variable_scope("foo"):
    tf.get_variable_scope().reuse_variables()
    v2 = tf.get_variable("v")

In [23]:
with tf.Session() as sess:
    sess.run(tf.variables_initializer([v2]))
    print(sess.run(v2)) 

-0.288421


# Data Input

## Import from numpy

In [24]:
a = np.array([[2,3,4], [5,6,7]])
print(a)

[[2 3 4]
 [5 6 7]]


In [25]:
ta = tf.convert_to_tensor(a)
print(ta)

Tensor("Const_6:0", shape=(2, 3), dtype=int64)


In [26]:
with tf.Session() as sess:
    print(sess.run(ta))

[[2 3 4]
 [5 6 7]]


## Placeholders

In [27]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)

output = tf.multiply(input1, input2)
with tf.Session() as sess:
    print(sess.run([output], feed_dict={input1:[7.], input2:[2.]}))

[array([ 14.], dtype=float32)]
