In [1]:
import tensorflow as tf
import numpy as np

In [2]:
def incr(k):
    with tf.variable_scope("conv1"):
        tb = tf.get_variable("b", (2,2), initializer=tf.constant_initializer(3))
        x = tb
        for _ in range(k):
            #print("AG")
            x = x + 1
        
        tupdate = tf.assign(tb, x)
        
    return (tb, tupdate, x)

In [3]:
sess = tf.Session()

In [4]:
a = np.array([[2,3,4], [5,6,7]])
ta = tf.convert_to_tensor(a)

print("ta : {0}".format(ta))

ta : Tensor("Const:0", shape=(2, 3), dtype=int32)


In [9]:
tc = tf.get_variable("c", (3,3), initializer=tf.constant_initializer(1))
tc2 = tc + 1
tc3 = tf.add(tc, tf.constant(1.0))
update = tf.assign(tc, tc3)
print("tc : {0}".format(tc))
print("tc2 : {0}".format(tc2))
print("tc3 : {0}".format(tc3))
print("update : {0}".format(update))

sess.run(tf.variables_initializer([tc]))
print(sess.run(tc))
print(sess.run(update))
print(sess.run(tc))

tc : <tf.Variable 'c:0' shape=(3, 3) dtype=float32_ref>
tc2 : Tensor("add_1:0", shape=(3, 3), dtype=float32)
tc3 : Tensor("Add_1:0", shape=(3, 3), dtype=float32)
update : Tensor("Assign_1:0", shape=(3, 3), dtype=float32_ref)
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]
[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]


In [6]:
tb, tu, tx = incr(10)
print("tb : {0}".format(tb))
print("tu : {0}".format(tu))
print("tx : {0}".format(tx))

tb : <tf.Variable 'conv1/b:0' shape=(2, 2) dtype=float32_ref>
tu : Tensor("conv1/Assign:0", shape=(2, 2), dtype=float32_ref)
tx : Tensor("conv1/add_9:0", shape=(2, 2), dtype=float32)


In [7]:
sess.run(tf.variables_initializer([tb]))
print(sess.run(tb))
print(sess.run(tx))
print(sess.run(tu))
print(sess.run(tx))
sess.run(tu)
print(sess.run(tb))

[[ 3.  3.]
 [ 3.  3.]]
[[ 13.  13.]
 [ 13.  13.]]
[[ 13.  13.]
 [ 13.  13.]]
[[ 23.  23.]
 [ 23.  23.]]
[[ 23.  23.]
 [ 23.  23.]]


In [8]:
tf.get_variable_scope().reuse_variables()
tb2, tu2, tx2 = incr(1000)
print(sess.run(tb2))
print(sess.run(tu2))
print(sess.run(tb2))
print(sess.run(tx2))

[[ 23.  23.]
 [ 23.  23.]]
[[ 1023.  1023.]
 [ 1023.  1023.]]
[[ 1023.  1023.]
 [ 1023.  1023.]]
[[ 2023.  2023.]
 [ 2023.  2023.]]
