* NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers.
* NumPy arrays are like Python's built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size. 
* It's a homogenous data storage
* It's mutable

In [1]:
l = [1,'hello',5.5]
# each element points to a piece of memory

In [2]:
t = (1,2,3,)
#t[0] =99 
#Immutable
l[0] = 88

In [3]:
import numpy as np

In [4]:
#Creating a numpy array from list
a = np.array([1,2,3,4,5])

In [5]:
type(a)

numpy.ndarray

In [6]:
a[1]

2

In [7]:
a[1]=99
#mutable

In [8]:
a

array([ 1, 99,  3,  4,  5])

In [9]:
#a[2] = 'abc'
#This won't work, since numpy is homogenous data storage

In [10]:
data = np.array([ [1,2,3], [4,5,6], [7,8,9]])

In [11]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
data.shape

(3, 3)

In [13]:
type(a.shape)
#tuple will have last element as ,

tuple

In [14]:
a[2:5]

array([3, 4, 5])

In [15]:
a[::-1]

array([ 5,  4,  3, 99,  1])

In [16]:
b = a 
# a & b, both points to same memory now
# if a is changed, b will also b changed

In [17]:
#Makes a separate copy of the data
b = a.copy()

In [18]:
b[3] = 1000

In [19]:
a

array([ 1, 99,  3,  4,  5])

In [20]:
b

array([   1,   99,    3, 1000,    5])

#### Reshaping of Data

In [21]:
data = np.arange(10)

In [22]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
data[::-1].reshape((2,5))
# data did not change
# it returned a new data with different dimension

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [24]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
data[: , np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [26]:
data.shape

(10,)

### Array Concatenation & Splitting

In [27]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [28]:
np.concatenate([x,y,x])

array([1, 2, 3, 3, 2, 1, 1, 2, 3])

In [29]:
grid = np.array([ [1,2,3],[5,6,7]])

In [30]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [31]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [5, 6, 7, 5, 6, 7]])

In [32]:
x = np.array([4,44,444])

In [33]:
grid

array([[1, 2, 3],
       [5, 6, 7]])

In [34]:
np.vstack([x,grid])

array([[  4,  44, 444],
       [  1,   2,   3],
       [  5,   6,   7]])

In [35]:
np.hstack([grid,grid,grid])
#hstack should have same height & can have different width

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [5, 6, 7, 5, 6, 7, 5, 6, 7]])

#### Splitting of arrays

In [36]:
x = [1,2,77,4,5,9,6,7,7,9]

In [37]:
a,b,c,d = np.split(x, [3,5,8])

In [38]:
a

array([ 1,  2, 77])

In [39]:
b

array([4, 5])

In [40]:
c

array([9, 6, 7])

In [41]:
d

array([7, 9])